# Generated by Django 3.2.8 on 2022-01-14 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20220114_0738'),
    ]

    operations = [
        
      
    ]
