# Generated by Django 3.2.8 on 2022-01-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20220114_0907'),
    ]

    operations = [
        
    
    ]
